import streamlit as st
import pandas as pd
import plotly.express as px
import io
import json
import zipfile
import textwrap

_PLOTLY_DARK = dict(
    paper_bgcolor="#0A0F1E",
    plot_bgcolor="#0D1526",
    font=dict(color="#94A3B8", family="Space Grotesk"),
    xaxis=dict(gridcolor="#1E293B", zerolinecolor="#1E293B"),
    yaxis=dict(gridcolor="#1E293B", zerolinecolor="#1E293B"),
    title_font=dict(size=14, color="#E2E8F0"),
)


def _header(title, sub):
    st.markdown(f"""
    <div class='page-header'>
        <div class='page-header-eyebrow'>// export & reports</div>
        <h2>{title}</h2>
        <div class='page-header-bar'></div>
        <p>{sub}</p>
    </div>""", unsafe_allow_html=True)


def _m_query(df: pd.DataFrame, filename: str) -> str:
    col_types = []
    for col in df.columns:
        dtype = df[col].dtype
        if pd.api.types.is_integer_dtype(dtype): pbi_type = "Int64.Type"
        elif pd.api.types.is_float_dtype(dtype): pbi_type = "type number"
        elif pd.api.types.is_datetime64_any_dtype(dtype): pbi_type = "type datetime"
        elif pd.api.types.is_bool_dtype(dtype): pbi_type = "type logical"
        else: pbi_type = "type text"
        col_types.append(f'        {{"{col}", {pbi_type}}}')
    types_str = ",\n".join(col_types)

    return textwrap.dedent(f"""
    // Power Query M Script — generated by DataViz Pro
    let
        Source = Excel.Workbook(
            File.Contents("C:\\\\Users\\\\YOU\\\\Downloads\\\\{filename}"),
            null, true
        ),
        CleanedData_Sheet = Source{{[Item="Cleaned Data", Kind="Sheet"]}}[Data],
        #"Promoted Headers" = Table.PromoteHeaders(CleanedData_Sheet, [PromoteAllScalars=true]),
        #"Changed Type" = Table.TransformColumnTypes(
            #"Promoted Headers",
            {{
    {types_str}
            }}
        )
    in
        #"Changed Type"
    """).strip()


def _dax_measures(df: pd.DataFrame) -> str:
    num_cols = df.select_dtypes(include="number").columns.tolist()
    if not num_cols:
        return "// No numeric columns found."
    lines = ["// ── Suggested DAX Measures — paste into Power BI Desktop ──\n"]
    for col in num_cols[:8]:
        lines += [
            f"// {col}",
            f"[Total {col}] = SUM('Table'[{col}])",
            f"[Avg {col}] = AVERAGE('Table'[{col}])",
            f"[Max {col}] = MAX('Table'[{col}])",
            f"[Min {col}] = MIN('Table'[{col}])",
            "",
        ]
    return "\n".join(lines)


def _build_report_html(df, filename, num_cols, cat_cols, miss):
    parts = ["""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DataViz Pro — Data Report</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Space Grotesk', system-ui, sans-serif;
         background: #060B1A; color: #A0AEC0; line-height: 1.55; padding: 24px; }
  header { background: #0A0F1E; padding: 28px 36px;
           border-radius: 14px; margin-bottom: 24px;
           border-left: 4px solid #00D4FF;
           border: 1px solid rgba(0,212,255,0.2); }
  header h1 { font-size: 1.5rem; font-weight: 700; color: #F0F6FF; }
  header p  { color: #64748B; font-size: 0.85rem; margin-top: 6px;
              font-family: 'JetBrains Mono', monospace; }
  .kpi-row { display: flex; gap: 14px; flex-wrap: wrap; margin-bottom: 20px; }
  .kpi { background: rgba(255,255,255,0.03); border-radius: 12px; padding: 16px 20px;
         border: 1px solid rgba(255,255,255,0.07); min-width: 130px; }
  .kpi-val { font-size: 1.6rem; font-weight: 700; }
  .kpi-lbl { font-size: 0.67rem; color: #4A5568; margin-top: 4px; font-weight: 600;
             text-transform: uppercase; letter-spacing: .1em;
             font-family: 'JetBrains Mono', monospace; }
  .card { background: #0A0F1E; border-radius: 12px; padding: 22px 24px;
          margin-bottom: 20px; border: 1px solid rgba(255,255,255,0.07); }
  .card h2 { font-size: .9rem; font-weight: 700; color: #E2E8F0;
             margin-bottom: 14px; padding-bottom: 8px;
             border-bottom: 1px solid rgba(255,255,255,0.06);
             font-family: 'JetBrains Mono', monospace;
             text-transform: uppercase; letter-spacing: .08em; }
  table { width: 100%; border-collapse: collapse; font-size: 0.8rem; }
  th { background: rgba(255,255,255,0.04); color: #E2E8F0; font-weight: 600;
       padding: 8px 10px; text-align: left;
       border-bottom: 1px solid rgba(255,255,255,0.08); }
  td { padding: 7px 10px; border-bottom: 1px solid rgba(255,255,255,0.04); color: #64748B; }
  tr:hover td { background: rgba(255,255,255,0.02); }
  footer { text-align: center; color: #2D3748; font-size: 0.75rem; margin-top: 30px;
           font-family: 'JetBrains Mono', monospace; }
</style>
</head>
<body>
"""]
    parts.append(f"""
<header>
  <h1>Data Report</h1>
  <p>Generated by DataViz Pro &nbsp;|&nbsp; Dataset: {filename}</p>
</header>
""")

    kpi_colors = ["#00D4FF","#A855F7","#10B981","#F59E0B","#FF006E","#0EA5E9"]
    kpis = [
        (f"{df.shape[0]:,}", "Rows"),
        (df.shape[1], "Columns"),
        (f"{df.isnull().mean().mean()*100:.1f}%", "Missing %"),
        (f"{df.duplicated().sum():,}", "Duplicates"),
        (len(num_cols), "Numeric cols"),
        (len(cat_cols), "Categorical cols"),
    ]
    parts.append('<div class="kpi-row">')
    for (val, lbl), color in zip(kpis, kpi_colors):
        parts.append(f'<div class="kpi"><div class="kpi-val" style="color:{color}">{val}</div><div class="kpi-lbl">{lbl}</div></div>')
    parts.append("</div>")

    if num_cols:
        desc = df[num_cols].describe(percentiles=[0.25, 0.5, 0.75]).T.round(3)
        parts.append('<div class="card"><h2>Numeric Statistics</h2>')
        parts.append(desc.to_html(classes="", border=0))
        parts.append("</div>")

    if not miss[miss > 0].empty:
        mdf = pd.DataFrame({
            "Column": miss[miss > 0].index,
            "Missing Count": miss[miss > 0].values,
            "Missing %": (miss[miss > 0].values / len(df) * 100).round(2),
        })
        parts.append('<div class="card"><h2>Missing Values</h2>')
        parts.append(mdf.to_html(index=False, classes="", border=0))
        parts.append("</div>")

    if num_cols:
        corr = df[num_cols].corr()
        fig_corr = px.imshow(corr, text_auto=".1f",
                              color_continuous_scale=["#FF006E","#0A0F1E","#00D4FF"],
                              zmin=-1, zmax=1, title="Correlation Matrix")
        fig_corr.update_layout(paper_bgcolor="#0A0F1E", plot_bgcolor="#0D1526", height=420,
                                font=dict(color="#94A3B8"))
        parts.append('<div class="card"><h2>Correlation Matrix</h2>')
        parts.append(fig_corr.to_html(full_html=False, include_plotlyjs="cdn"))
        parts.append("</div>")

        for nc in num_cols[:4]:
            fh = px.histogram(df, x=nc, nbins=40, title=f"Distribution: {nc}",
                              color_discrete_sequence=["#00D4FF"])
            fh.update_layout(paper_bgcolor="#0A0F1E", plot_bgcolor="#0D1526", height=340,
                              font=dict(color="#94A3B8"))
            parts.append(f'<div class="card"><h2>{nc} — Distribution</h2>')
            parts.append(fh.to_html(full_html=False, include_plotlyjs=False))
            parts.append("</div>")

    if cat_cols:
        for cc in cat_cols[:2]:
            vc = df[cc].value_counts().head(12)
            fb = px.bar(x=vc.values, y=vc.index, orientation="h",
                        title=f"Top values: {cc}",
                        color_discrete_sequence=["#A855F7"])
            fb.update_layout(paper_bgcolor="#0A0F1E", plot_bgcolor="#0D1526", height=340,
                             yaxis={"categoryorder": "total ascending"},
                             font=dict(color="#94A3B8"))
            parts.append(f'<div class="card"><h2>{cc} — Value Counts</h2>')
            parts.append(fb.to_html(full_html=False, include_plotlyjs=False))
            parts.append("</div>")

    parts.append("<footer>Generated by DataViz Pro</footer></body></html>")
    return "\n".join(parts)


def export_page():
    _header("Export & Reports", "Download data, charts, Power BI files, and full HTML reports")

    if st.session_state.df is None:
        st.warning("Please upload a dataset first.")
        return

    df   = st.session_state.df
    raw  = st.session_state.raw_df
    filename = st.session_state.filename or "data"
    base = filename.rsplit(".", 1)[0]

    m1, m2, m3 = st.columns(3)
    m1.metric("Current rows", f"{df.shape[0]:,}")
    m2.metric("Original rows", f"{raw.shape[0]:,}")
    diff = df.shape[0] - raw.shape[0]
    m3.metric("Rows changed", str(diff), delta=str(diff))

    st.markdown("<br>", unsafe_allow_html=True)

    tab1, tab2, tab3, tab4 = st.tabs(["Data Export", "Chart Export", "Power BI", "Full HTML Report"])

    with tab1:
        fmt = st.radio("Format", ["CSV", "Excel (.xlsx)", "JSON", "Parquet"], horizontal=True)
        include_index = st.checkbox("Include row index", False)

        if fmt == "CSV":
            sep = st.selectbox("Separator", [",", ";", "\t", "|"])
            buf = io.BytesIO()
            df.to_csv(buf, index=include_index, sep=sep)
            buf.seek(0)
            st.download_button("Download CSV", data=buf,
                               file_name=f"{base}_cleaned.csv", mime="text/csv",
                               use_container_width=True)

        elif fmt == "Excel (.xlsx)":
            inc_orig = st.checkbox("Include original data on second sheet", True)
            buf = io.BytesIO()
            with pd.ExcelWriter(buf, engine="xlsxwriter") as writer:
                df.to_excel(writer, index=include_index, sheet_name="Cleaned Data")
                if inc_orig:
                    raw.to_excel(writer, index=include_index, sheet_name="Original Data")
            buf.seek(0)
            st.download_button("Download Excel", data=buf,
                               file_name=f"{base}_cleaned.xlsx",
                               mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                               use_container_width=True)

        elif fmt == "JSON":
            orient = st.selectbox("Orientation", ["records", "split", "index", "columns"])
            json_str = df.to_json(orient=orient, indent=2)
            st.download_button("Download JSON", data=json_str.encode(),
                               file_name=f"{base}_cleaned.json", mime="application/json",
                               use_container_width=True)

        elif fmt == "Parquet":
            buf = io.BytesIO()
            df.to_parquet(buf, index=include_index)
            buf.seek(0)
            st.download_button("Download Parquet", data=buf,
                               file_name=f"{base}_cleaned.parquet",
                               mime="application/octet-stream",
                               use_container_width=True)

        st.markdown("---")
        st.markdown("<span style='color:#A0AEC0;font-weight:600;font-size:.83rem;'>Preview (first 10 rows)</span>", unsafe_allow_html=True)
        st.dataframe(df.head(10), use_container_width=True)

    with tab2:
        num_cols = df.select_dtypes(include="number").columns.tolist()
        cat_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
        template = st.selectbox("Chart theme", ["plotly_dark", "plotly_white", "plotly", "ggplot2", "seaborn"])
        chart_type = st.selectbox("Chart type", ["Bar", "Line", "Scatter", "Pie", "Box", "Histogram", "Violin", "Treemap"])

        fig = None
        NEON = ["#00D4FF","#7C3AED","#FF006E","#10B981","#F59E0B"]

        if chart_type == "Bar" and cat_cols and num_cols:
            x = st.selectbox("X", cat_cols, key="ce_x")
            y = st.selectbox("Y", num_cols, key="ce_y")
            fig = px.bar(df.groupby(x)[y].mean().reset_index(), x=x, y=y,
                         template=template, text_auto=True, color_discrete_sequence=["#00D4FF"])
        elif chart_type == "Line" and num_cols:
            x = st.selectbox("X", df.columns.tolist(), key="ce_x")
            y = st.selectbox("Y", num_cols, key="ce_y")
            fig = px.line(df.sort_values(x), x=x, y=y, template=template,
                          color_discrete_sequence=["#00D4FF"])
        elif chart_type == "Scatter" and len(num_cols) >= 2:
            x = st.selectbox("X", num_cols, key="ce_x")
            y = st.selectbox("Y", [c for c in num_cols if c != x], key="ce_y")
            fig = px.scatter(df, x=x, y=y, template=template, opacity=0.7,
                             color_discrete_sequence=["#00D4FF"])
        elif chart_type == "Pie" and cat_cols and num_cols:
            n = st.selectbox("Labels", cat_cols, key="ce_n")
            v = st.selectbox("Values", num_cols, key="ce_v")
            fig = px.pie(df.groupby(n)[v].sum().reset_index(), names=n, values=v,
                         template=template, hole=0.4, color_discrete_sequence=NEON)
        elif chart_type == "Box" and num_cols:
            y = st.selectbox("Column", num_cols, key="ce_y")
            fig = px.box(df, y=y, template=template, color_discrete_sequence=["#00D4FF"])
        elif chart_type == "Histogram" and num_cols:
            col = st.selectbox("Column", num_cols, key="ce_col")
            fig = px.histogram(df, x=col, nbins=40, template=template,
                               color_discrete_sequence=["#00D4FF"])
        elif chart_type == "Violin" and num_cols:
            y = st.selectbox("Column", num_cols, key="ce_y")
            x = st.selectbox("Group by", ["None"] + cat_cols, key="ce_x")
            fig = px.violin(df, y=y, x=x if x != "None" else None, box=True,
                            template=template, color_discrete_sequence=NEON)
        elif chart_type == "Treemap" and cat_cols and num_cols:
            path = st.multiselect("Hierarchy", cat_cols, default=cat_cols[:min(2, len(cat_cols))])
            val = st.selectbox("Values", num_cols, key="ce_val")
            if path:
                fig = px.treemap(df, path=[px.Constant("All")] + path, values=val,
                                 template=template,
                                 color_continuous_scale=["#1E293B","#7C3AED","#00D4FF"])

        if fig:
            fig.update_layout(height=420, **_PLOTLY_DARK)
            st.plotly_chart(fig, use_container_width=True)
            buf = io.StringIO()
            fig.write_html(buf)
            st.download_button("Download Chart HTML", data=buf.getvalue().encode(),
                               file_name=f"{base}_chart.html", mime="text/html",
                               use_container_width=True)

    with tab3:
        st.markdown("""
        <div style='background:rgba(0,212,255,0.05);border:1px solid rgba(0,212,255,0.18);
                    border-radius:12px;padding:1rem 1.3rem;margin-bottom:1.2rem;'>
            <div style='font-weight:700;color:#00D4FF;margin-bottom:8px;font-size:.85rem;'>How to import into Power BI</div>
            <ol style='color:#64748B;font-size:.82rem;line-height:2;margin-left:1rem;'>
                <li>Download the <b style="color:#A0AEC0;">Excel file</b> below</li>
                <li>Open <b style="color:#A0AEC0;">Power BI Desktop → Home → Get Data → Excel Workbook</b></li>
                <li>Select the downloaded file and choose the <b style="color:#A0AEC0;">"Cleaned Data"</b> sheet</li>
                <li>Open the <b style="color:#A0AEC0;">Advanced Editor</b> and paste the <b style="color:#A0AEC0;">M Query</b> below</li>
                <li>Copy the <b style="color:#A0AEC0;">DAX Measures</b> and create them in your report</li>
            </ol>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("<span style='color:#A0AEC0;font-weight:600;font-size:.83rem;'>Step 1 — Download Power BI-ready Excel</span>", unsafe_allow_html=True)
        buf = io.BytesIO()
        with pd.ExcelWriter(buf, engine="xlsxwriter") as writer:
            df.to_excel(writer, index=False, sheet_name="Cleaned Data")
            ws = writer.sheets["Cleaned Data"]
            wb = writer.book
            header_fmt = wb.add_format({
                "bold": True, "bg_color": "#0A0F1E", "font_color": "#00D4FF",
                "border": 1, "border_color": "#1E293B"
            })
            for col_num, col_name in enumerate(df.columns):
                ws.write(0, col_num, col_name, header_fmt)
                ws.set_column(col_num, col_num, max(14, len(str(col_name)) + 4))
        buf.seek(0)
        st.download_button("Download Power BI Excel (.xlsx)", data=buf,
                           file_name=f"{base}_powerbi.xlsx",
                           mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                           use_container_width=True)

        st.markdown("---")
        st.markdown("<span style='color:#A0AEC0;font-weight:600;font-size:.83rem;'>Step 2 — Power Query M Script</span>", unsafe_allow_html=True)
        m_script = _m_query(df, f"{base}_powerbi.xlsx")
        st.code(m_script, language="text")

        st.markdown("---")
        st.markdown("<span style='color:#A0AEC0;font-weight:600;font-size:.83rem;'>Step 3 — Suggested DAX Measures</span>", unsafe_allow_html=True)
        dax = _dax_measures(df)
        st.code(dax, language="text")

        st.markdown("---")
        st.markdown("<span style='color:#A0AEC0;font-weight:600;font-size:.83rem;'>Download Everything as a ZIP Bundle</span>", unsafe_allow_html=True)
        zip_buf = io.BytesIO()
        with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
            xl_buf = io.BytesIO()
            with pd.ExcelWriter(xl_buf, engine="xlsxwriter") as writer:
                df.to_excel(writer, index=False, sheet_name="Cleaned Data")
            zf.writestr(f"{base}_powerbi.xlsx", xl_buf.getvalue())
            zf.writestr(f"{base}_mquery.txt", m_script)
            zf.writestr(f"{base}_dax_measures.txt", dax)
            zf.writestr(f"{base}_data.csv", df.to_csv(index=False))
        zip_buf.seek(0)
        st.download_button("Download Power BI Bundle (.zip)", data=zip_buf,
                           file_name=f"{base}_powerbi_bundle.zip",
                           mime="application/zip", use_container_width=True)

    with tab4:
        st.info("Generates a self-contained HTML report with KPI cards, statistics, correlation matrix, and distribution charts — share with anyone, no tools needed.")
        num_cols = df.select_dtypes(include="number").columns.tolist()
        cat_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
        miss     = df.isnull().sum()

        if st.button("Generate HTML Report", type="primary", use_container_width=True):
            with st.spinner("Building report…"):
                html = _build_report_html(df, filename, num_cols, cat_cols, miss)
            st.success("Report ready!")
            st.download_button("Download Full HTML Report", data=html.encode(),
                               file_name=f"{base}_report.html", mime="text/html",
                               use_container_width=True)
