import streamlit as st
import pandas as pd
import plotly.express as px
import io
import json
import zipfile
import textwrap


def _header(title, sub):
    st.markdown(f"<div class='page-header'><h2>{title}</h2><p>{sub}</p></div>", unsafe_allow_html=True)


# ── Power BI helpers ──────────────────────────────────────────────────────────

def _m_query(df: pd.DataFrame, filename: str) -> str:
    """Generate a Power Query M script for the dataset."""
    col_types = []
    for col in df.columns:
        dtype = df[col].dtype
        if pd.api.types.is_integer_dtype(dtype):
            pbi_type = "Int64.Type"
        elif pd.api.types.is_float_dtype(dtype):
            pbi_type = "type number"
        elif pd.api.types.is_datetime64_any_dtype(dtype):
            pbi_type = "type datetime"
        elif pd.api.types.is_bool_dtype(dtype):
            pbi_type = "type logical"
        else:
            pbi_type = "type text"
        col_types.append(f'        {{"{col}", {pbi_type}}}')
    types_str = ",\n".join(col_types)

    return textwrap.dedent(f"""
    // Power Query M Script — generated by DataViz Pro
    // HOW TO USE:
    //   1. Open Power BI Desktop
    //   2. Home → Get Data → Excel Workbook (or CSV)
    //   3. Select the exported file: {filename}
    //   4. In the Query Editor, open Advanced Editor and paste this script

    let
        Source = Excel.Workbook(
            File.Contents("C:\\\\Users\\\\YOU\\\\Downloads\\\\{filename}"),
            null,
            true
        ),
        CleanedData_Sheet = Source{{[Item="Cleaned Data", Kind="Sheet"]}}[Data],
        #"Promoted Headers" = Table.PromoteHeaders(
            CleanedData_Sheet,
            [PromoteAllScalars=true]
        ),
        #"Changed Type" = Table.TransformColumnTypes(
            #"Promoted Headers",
            {{
    {types_str}
            }}
        )
    in
        #"Changed Type"
    """).strip()


def _dax_measures(df: pd.DataFrame) -> str:
    """Suggest DAX measures for numeric columns."""
    num_cols = df.select_dtypes(include="number").columns.tolist()
    if not num_cols:
        return "// No numeric columns found for DAX measure suggestions."

    lines = ["// ── Suggested DAX Measures — paste into Power BI Desktop ──────────────────\n"]
    for col in num_cols[:8]:
        safe = col.replace(" ", "_")
        lines += [
            f"// {col}",
            f"[Total {col}] = SUM('Table'[{col}])",
            f"[Avg {col}] = AVERAGE('Table'[{col}])",
            f"[Max {col}] = MAX('Table'[{col}])",
            f"[Min {col}] = MIN('Table'[{col}])",
            "",
        ]
    return "\n".join(lines)


def _build_report_html(df, filename, num_cols, cat_cols, miss):
    """Build a standalone HTML data report."""
    parts = ["""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>DataViz Pro — Data Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; background: #F1F5F9;
         color: #334155; line-height: 1.55; padding: 24px; }
  header { background: #0F172A; color: white; padding: 28px 36px;
           border-radius: 12px; margin-bottom: 24px; border-left: 6px solid #0EA5E9; }
  header h1 { font-size: 1.7rem; font-weight: 800; }
  header p  { color: #94A3B8; font-size: 0.9rem; margin-top: 6px; }
  .kpi-row { display: flex; gap: 14px; flex-wrap: wrap; margin-bottom: 20px; }
  .kpi { background: white; border-radius: 10px; padding: 16px 22px;
         border-top: 3px solid #0EA5E9; box-shadow: 0 1px 4px rgba(0,0,0,.06);
         min-width: 130px; }
  .kpi-val { font-size: 1.7rem; font-weight: 800; color: #0F172A; }
  .kpi-lbl { font-size: 0.75rem; color: #64748B; margin-top: 4px; font-weight: 500;
             text-transform: uppercase; letter-spacing: .04em; }
  .card { background: white; border-radius: 12px; padding: 22px 24px;
          margin-bottom: 20px; box-shadow: 0 1px 4px rgba(0,0,0,.06); }
  .card h2 { font-size: 1rem; font-weight: 700; color: #0F172A;
             margin-bottom: 14px; padding-bottom: 8px;
             border-bottom: 1px solid #F1F5F9; }
  table { width: 100%; border-collapse: collapse; font-size: 0.82rem; }
  th { background: #F8FAFC; color: #0F172A; font-weight: 600;
       padding: 8px 10px; text-align: left; border-bottom: 2px solid #E2E8F0; }
  td { padding: 7px 10px; border-bottom: 1px solid #F1F5F9; color: #475569; }
  tr:hover td { background: #F8FAFC; }
  .badge { display: inline-block; background: #EFF6FF; color: #3B82F6;
           border-radius: 4px; padding: 2px 7px; font-size: 0.74rem; font-weight: 600; }
  footer { text-align: center; color: #94A3B8; font-size: 0.78rem; margin-top: 30px; }
</style>
</head>
<body>
"""]
    parts.append(f"""
<header>
  <h1>Data Report</h1>
  <p>Generated by DataViz Pro &nbsp;|&nbsp; Dataset: {filename}</p>
</header>
""")

    kpi_colors = ["#0EA5E9", "#F59E0B", "#10B981", "#8B5CF6", "#EF4444", "#06B6D4"]
    kpis = [
        (f"{df.shape[0]:,}", "Rows"),
        (df.shape[1], "Columns"),
        (f"{df.isnull().mean().mean()*100:.1f}%", "Missing %"),
        (f"{df.duplicated().sum():,}", "Duplicates"),
        (len(num_cols), "Numeric cols"),
        (len(cat_cols), "Categorical cols"),
    ]
    parts.append('<div class="kpi-row">')
    for (val, lbl), color in zip(kpis, kpi_colors):
        parts.append(f'<div class="kpi" style="border-top-color:{color}"><div class="kpi-val">{val}</div><div class="kpi-lbl">{lbl}</div></div>')
    parts.append("</div>")

    # Numeric stats
    if num_cols:
        desc = df[num_cols].describe(percentiles=[0.25, 0.5, 0.75]).T.round(3)
        parts.append('<div class="card"><h2>Numeric Statistics</h2>')
        parts.append(desc.to_html(classes="", border=0))
        parts.append("</div>")

    # Missing values table
    if not miss[miss > 0].empty:
        mdf = pd.DataFrame({
            "Column": miss[miss > 0].index,
            "Missing Count": miss[miss > 0].values,
            "Missing %": (miss[miss > 0].values / len(df) * 100).round(2),
        })
        parts.append('<div class="card"><h2>Missing Values</h2>')
        parts.append(mdf.to_html(index=False, classes="", border=0))
        parts.append("</div>")

    # Plotly charts
    if num_cols:
        corr = df[num_cols].corr()
        fig_corr = px.imshow(corr, text_auto=".1f", color_continuous_scale="RdBu_r",
                              zmin=-1, zmax=1, title="Correlation Matrix")
        fig_corr.update_layout(paper_bgcolor="white", plot_bgcolor="#F8FAFC", height=420)
        parts.append('<div class="card"><h2>Correlation Matrix</h2>')
        parts.append(fig_corr.to_html(full_html=False, include_plotlyjs="cdn"))
        parts.append("</div>")

        for nc in num_cols[:4]:
            fh = px.histogram(df, x=nc, nbins=40, title=f"Distribution: {nc}",
                              color_discrete_sequence=["#0EA5E9"])
            fh.update_layout(paper_bgcolor="white", plot_bgcolor="#F8FAFC", height=340)
            parts.append(f'<div class="card"><h2>{nc} — Distribution</h2>')
            parts.append(fh.to_html(full_html=False, include_plotlyjs=False))
            parts.append("</div>")

    if cat_cols:
        for cc in cat_cols[:2]:
            vc = df[cc].value_counts().head(12)
            fb = px.bar(x=vc.values, y=vc.index, orientation="h",
                        title=f"Top values: {cc}",
                        color_discrete_sequence=["#F59E0B"])
            fb.update_layout(paper_bgcolor="white", plot_bgcolor="#F8FAFC", height=340,
                             yaxis={"categoryorder": "total ascending"})
            parts.append(f'<div class="card"><h2>{cc} — Value Counts</h2>')
            parts.append(fb.to_html(full_html=False, include_plotlyjs=False))
            parts.append("</div>")

    parts.append("<footer>Generated by DataViz Pro</footer></body></html>")
    return "\n".join(parts)


# ── Main page ─────────────────────────────────────────────────────────────────

def export_page():
    _header("Export & Reports", "Download data, charts, Power BI files, and full HTML reports")

    if st.session_state.df is None:
        st.warning("Please upload a dataset first.")
        return

    df   = st.session_state.df
    raw  = st.session_state.raw_df
    filename = st.session_state.filename or "data"
    base = filename.rsplit(".", 1)[0]

    m1, m2, m3 = st.columns(3)
    m1.metric("Current rows", f"{df.shape[0]:,}")
    m2.metric("Original rows", f"{raw.shape[0]:,}")
    diff = df.shape[0] - raw.shape[0]
    m3.metric("Rows changed", str(diff), delta=str(diff))

    st.markdown("<br>", unsafe_allow_html=True)

    tab1, tab2, tab3, tab4 = st.tabs(["Data Export", "Chart Export", "Power BI", "Full HTML Report"])

    # ── TAB 1 : Data export ──────────────────────────────────────────────
    with tab1:
        fmt = st.radio("Format", ["CSV", "Excel (.xlsx)", "JSON", "Parquet"], horizontal=True)
        include_index = st.checkbox("Include row index", False)

        if fmt == "CSV":
            sep = st.selectbox("Separator", [",", ";", "\t", "|"])
            buf = io.BytesIO()
            df.to_csv(buf, index=include_index, sep=sep)
            buf.seek(0)
            st.download_button("Download CSV", data=buf,
                               file_name=f"{base}_cleaned.csv", mime="text/csv",
                               use_container_width=True)

        elif fmt == "Excel (.xlsx)":
            inc_orig = st.checkbox("Include original data on second sheet", True)
            buf = io.BytesIO()
            with pd.ExcelWriter(buf, engine="xlsxwriter") as writer:
                df.to_excel(writer, index=include_index, sheet_name="Cleaned Data")
                if inc_orig:
                    raw.to_excel(writer, index=include_index, sheet_name="Original Data")
            buf.seek(0)
            st.download_button("Download Excel", data=buf,
                               file_name=f"{base}_cleaned.xlsx",
                               mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                               use_container_width=True)

        elif fmt == "JSON":
            orient = st.selectbox("Orientation", ["records", "split", "index", "columns"])
            json_str = df.to_json(orient=orient, indent=2)
            st.download_button("Download JSON", data=json_str.encode(),
                               file_name=f"{base}_cleaned.json", mime="application/json",
                               use_container_width=True)

        elif fmt == "Parquet":
            buf = io.BytesIO()
            df.to_parquet(buf, index=include_index)
            buf.seek(0)
            st.download_button("Download Parquet", data=buf,
                               file_name=f"{base}_cleaned.parquet",
                               mime="application/octet-stream",
                               use_container_width=True)

        st.markdown("---")
        st.markdown("**Preview (first 10 rows)**")
        st.dataframe(df.head(10), use_container_width=True)

    # ── TAB 2 : Chart export ─────────────────────────────────────────────
    with tab2:
        num_cols = df.select_dtypes(include="number").columns.tolist()
        cat_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
        template = st.selectbox("Chart theme", ["plotly_white", "plotly", "plotly_dark", "ggplot2", "seaborn"])
        chart_type = st.selectbox("Chart type", ["Bar", "Line", "Scatter", "Pie", "Box", "Histogram", "Violin", "Treemap"])

        fig = None
        if chart_type == "Bar" and cat_cols and num_cols:
            x = st.selectbox("X", cat_cols, key="ce_x")
            y = st.selectbox("Y", num_cols, key="ce_y")
            fig = px.bar(df.groupby(x)[y].mean().reset_index(), x=x, y=y,
                         template=template, text_auto=True, color_discrete_sequence=["#0EA5E9"])
        elif chart_type == "Line" and num_cols:
            x = st.selectbox("X", df.columns.tolist(), key="ce_x")
            y = st.selectbox("Y", num_cols, key="ce_y")
            fig = px.line(df.sort_values(x), x=x, y=y, template=template)
        elif chart_type == "Scatter" and len(num_cols) >= 2:
            x = st.selectbox("X", num_cols, key="ce_x")
            y = st.selectbox("Y", [c for c in num_cols if c != x], key="ce_y")
            fig = px.scatter(df, x=x, y=y, template=template, opacity=0.7)
        elif chart_type == "Pie" and cat_cols and num_cols:
            n = st.selectbox("Labels", cat_cols, key="ce_n")
            v = st.selectbox("Values", num_cols, key="ce_v")
            fig = px.pie(df.groupby(n)[v].sum().reset_index(), names=n, values=v, template=template, hole=0.4)
        elif chart_type == "Box" and num_cols:
            y = st.selectbox("Column", num_cols, key="ce_y")
            fig = px.box(df, y=y, template=template)
        elif chart_type == "Histogram" and num_cols:
            col = st.selectbox("Column", num_cols, key="ce_col")
            fig = px.histogram(df, x=col, nbins=40, template=template, color_discrete_sequence=["#0EA5E9"])
        elif chart_type == "Violin" and num_cols:
            y = st.selectbox("Column", num_cols, key="ce_y")
            x = st.selectbox("Group by", ["None"] + cat_cols, key="ce_x")
            fig = px.violin(df, y=y, x=x if x != "None" else None, box=True, template=template)
        elif chart_type == "Treemap" and cat_cols and num_cols:
            path = st.multiselect("Hierarchy", cat_cols, default=cat_cols[:min(2, len(cat_cols))])
            val = st.selectbox("Values", num_cols, key="ce_val")
            if path:
                fig = px.treemap(df, path=[px.Constant("All")] + path, values=val, template=template)

        if fig:
            fig.update_layout(height=420, plot_bgcolor="#F8FAFC", paper_bgcolor="#FFFFFF")
            st.plotly_chart(fig, use_container_width=True)
            buf = io.StringIO()
            fig.write_html(buf)
            st.download_button("Download Chart HTML", data=buf.getvalue().encode(),
                               file_name=f"{base}_chart.html", mime="text/html",
                               use_container_width=True)

    # ── TAB 3 : Power BI ─────────────────────────────────────────────────
    with tab3:
        st.markdown("""
        <div style='background:#EFF6FF;border:1px solid #BFDBFE;border-radius:10px;
                    padding:1rem 1.3rem;margin-bottom:1.2rem;'>
            <div style='font-weight:700;color:#1E40AF;margin-bottom:6px;'>How to import into Power BI</div>
            <ol style='color:#1E3A8A;font-size:0.85rem;line-height:1.8;margin-left:1rem;'>
                <li>Download the <b>Excel file</b> below</li>
                <li>Open <b>Power BI Desktop → Home → Get Data → Excel Workbook</b></li>
                <li>Select the downloaded file and choose the <b>"Cleaned Data"</b> sheet</li>
                <li>Optionally, open the <b>Advanced Editor</b> and paste the <b>M Query</b> below for typed columns</li>
                <li>Copy the <b>DAX Measures</b> and create them in your report</li>
            </ol>
        </div>
        """, unsafe_allow_html=True)

        # Excel download (Power BI optimised)
        st.markdown("#### Step 1 — Download Power BI-ready Excel")
        buf = io.BytesIO()
        with pd.ExcelWriter(buf, engine="xlsxwriter") as writer:
            df.to_excel(writer, index=False, sheet_name="Cleaned Data")
            ws = writer.sheets["Cleaned Data"]
            wb = writer.book
            header_fmt = wb.add_format({
                "bold": True, "bg_color": "#0F172A", "font_color": "#FFFFFF",
                "border": 1, "border_color": "#E2E8F0"
            })
            for col_num, col_name in enumerate(df.columns):
                ws.write(0, col_num, col_name, header_fmt)
                ws.set_column(col_num, col_num, max(14, len(str(col_name)) + 4))
        buf.seek(0)
        st.download_button(
            "Download Power BI Excel (.xlsx)",
            data=buf,
            file_name=f"{base}_powerbi.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
        )

        st.markdown("---")
        # M Query
        st.markdown("#### Step 2 — Power Query M Script")
        st.info("Copy this script and paste it into Power BI's **Advanced Editor** (in the Power Query window).")
        m_script = _m_query(df, f"{base}_powerbi.xlsx")
        st.code(m_script, language="text")

        # DAX measures
        st.markdown("---")
        st.markdown("#### Step 3 — Suggested DAX Measures")
        st.info("In Power BI Desktop: **Modeling → New Measure**, then paste each measure below.")
        dax = _dax_measures(df)
        st.code(dax, language="text")

        # ZIP bundle
        st.markdown("---")
        st.markdown("#### Download Everything as a ZIP Bundle")
        zip_buf = io.BytesIO()
        with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
            # Excel
            xl_buf = io.BytesIO()
            with pd.ExcelWriter(xl_buf, engine="xlsxwriter") as writer:
                df.to_excel(writer, index=False, sheet_name="Cleaned Data")
            zf.writestr(f"{base}_powerbi.xlsx", xl_buf.getvalue())
            # M Query
            zf.writestr(f"{base}_mquery.txt", m_script)
            # DAX
            zf.writestr(f"{base}_dax_measures.txt", dax)
            # CSV fallback
            csv_str = df.to_csv(index=False)
            zf.writestr(f"{base}_data.csv", csv_str)
            # README
            readme = textwrap.dedent(f"""
                DataViz Pro — Power BI Export Bundle
                =====================================
                Files included:
                  {base}_powerbi.xlsx   Excel file ready for Power BI import
                  {base}_mquery.txt     Power Query M script (paste in Advanced Editor)
                  {base}_dax_measures.txt  Suggested DAX measures
                  {base}_data.csv       CSV fallback

                Dataset: {st.session_state.filename}
                Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}
            """).strip()
            zf.writestr("README.txt", readme)
        zip_buf.seek(0)
        st.download_button(
            "Download Power BI Bundle (.zip)",
            data=zip_buf,
            file_name=f"{base}_powerbi_bundle.zip",
            mime="application/zip",
            use_container_width=True,
        )

    # ── TAB 4 : Full HTML report ─────────────────────────────────────────
    with tab4:
        st.info("Generates a self-contained HTML report with KPI cards, statistics tables, correlation matrix, and distribution charts — share it with anyone, no tools needed.")

        num_cols = df.select_dtypes(include="number").columns.tolist()
        cat_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
        miss     = df.isnull().sum()

        if st.button("Generate HTML Report", type="primary", use_container_width=True):
            with st.spinner("Building report…"):
                html = _build_report_html(df, filename, num_cols, cat_cols, miss)
            st.success("Report ready!")
            st.download_button(
                "Download Full HTML Report",
                data=html.encode(),
                file_name=f"{base}_report.html",
                mime="text/html",
                use_container_width=True,
            )
