from flask import Blueprint, request, jsonify, send_file, make_response
import pandas as pd
import numpy as np
import io, json, zipfile, traceback
from api.store import get_store

export_bp = Blueprint("export", __name__, url_prefix="/api/export")

def _df(): return get_store().get("df")

@export_bp.route("/csv")
def export_csv():
    df = _df()
    if df is None: return jsonify(error="No dataset"), 400
    buf = io.StringIO()
    df.to_csv(buf, index=False)
    resp = make_response(buf.getvalue())
    resp.headers["Content-Type"] = "text/csv"
    fn = get_store().get("filename","dataset").rsplit(".",1)[0]
    resp.headers["Content-Disposition"] = f"attachment; filename={fn}_cleaned.csv"
    return resp

@export_bp.route("/excel")
def export_excel():
    df = _df()
    if df is None: return jsonify(error="No dataset"), 400
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as w:
        df.to_excel(w, index=False, sheet_name="Data")
        # stats sheet
        num = df.select_dtypes(include="number")
        if len(num.columns):
            num.describe().to_excel(w, sheet_name="Statistics")
    buf.seek(0)
    fn = get_store().get("filename","dataset").rsplit(".",1)[0]
    return send_file(buf, download_name=f"{fn}_export.xlsx",
                     as_attachment=True, mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")

@export_bp.route("/json")
def export_json():
    df = _df()
    if df is None: return jsonify(error="No dataset"), 400
    d = df.where(pd.notnull(df), None)
    resp = make_response(d.to_json(orient="records", indent=2))
    resp.headers["Content-Type"] = "application/json"
    fn = get_store().get("filename","dataset").rsplit(".",1)[0]
    resp.headers["Content-Disposition"] = f"attachment; filename={fn}.json"
    return resp

@export_bp.route("/parquet")
def export_parquet():
    df = _df()
    if df is None: return jsonify(error="No dataset"), 400
    buf = io.BytesIO()
    df.to_parquet(buf, index=False)
    buf.seek(0)
    fn = get_store().get("filename","dataset").rsplit(".",1)[0]
    return send_file(buf, download_name=f"{fn}.parquet",
                     as_attachment=True, mimetype="application/octet-stream")

@export_bp.route("/html-report")
def export_html():
    df = _df()
    if df is None: return jsonify(error="No dataset"), 400
    try:
        store = get_store()
        fn = store.get("filename","dataset")
        num = df.select_dtypes(include="number")
        stats = num.describe().round(4).to_html(classes="stats-table", border=0) if len(num.columns) else "<p>No numeric columns</p>"
        preview = df.head(50).to_html(classes="data-table", border=0, index=False)
        miss = df.isna().sum()
        miss_html = miss[miss>0].to_frame("Missing").to_html(classes="stats-table", border=0)
        html = f"""<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"><title>DataViz Pro Report — {fn}</title>
<style>
body{{font-family:system-ui,sans-serif;background:#060B1A;color:#E2E8F0;padding:2rem;}}
h1{{color:#00D4FF;border-bottom:2px solid #7C3AED;padding-bottom:.5rem;}}
h2{{color:#7C3AED;margin-top:2rem;}}
.stats-table,.data-table{{width:100%;border-collapse:collapse;font-size:.85rem;margin:.5rem 0;}}
.stats-table th,.data-table th{{background:#0D1528;color:#00D4FF;padding:.4rem .6rem;text-align:left;}}
.stats-table td,.data-table td{{padding:.3rem .6rem;border-bottom:1px solid #1E293B;}}
.card{{background:#0D1528;border:1px solid #1E293B;border-radius:8px;padding:1.5rem;margin:1rem 0;}}
.kpi{{display:inline-block;background:#0D1528;border:1px solid #00D4FF33;border-radius:8px;padding:1rem 2rem;margin:.5rem;text-align:center;}}
.kpi-val{{font-size:2rem;color:#00D4FF;font-weight:700;}}
.kpi-lbl{{color:#94A3B8;font-size:.85rem;margin-top:.2rem;}}
</style></head><body>
<h1>DataViz Pro — Data Report</h1>
<div class="card">
  <span class="kpi"><div class="kpi-val">{len(df):,}</div><div class="kpi-lbl">Rows</div></span>
  <span class="kpi"><div class="kpi-val">{len(df.columns)}</div><div class="kpi-lbl">Columns</div></span>
  <span class="kpi"><div class="kpi-val">{df.isna().sum().sum():,}</div><div class="kpi-lbl">Missing Values</div></span>
  <span class="kpi"><div class="kpi-val">{df.duplicated().sum():,}</div><div class="kpi-lbl">Duplicate Rows</div></span>
</div>
<h2>Data Preview (first 50 rows)</h2><div class="card">{preview}</div>
<h2>Statistical Summary</h2><div class="card">{stats}</div>
<h2>Missing Values</h2><div class="card">{miss_html if len(miss[miss>0]) else "<p>No missing values!</p>"}</div>
<p style="color:#475569;font-size:.75rem;margin-top:3rem;">Generated by DataViz Pro · {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
</body></html>"""
        resp = make_response(html)
        resp.headers["Content-Type"] = "text/html"
        resp.headers["Content-Disposition"] = f"attachment; filename=report_{fn}.html"
        return resp
    except Exception as e:
        return jsonify(error=str(e)), 500

@export_bp.route("/zip")
def export_zip():
    df = _df()
    if df is None: return jsonify(error="No dataset"), 400
    try:
        store = get_store()
        fn = store.get("filename","dataset").rsplit(".",1)[0]
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            # CSV
            csv_buf = io.StringIO(); df.to_csv(csv_buf, index=False)
            zf.writestr(f"{fn}.csv", csv_buf.getvalue())
            # JSON
            j = df.where(pd.notnull(df), None).to_json(orient="records", indent=2)
            zf.writestr(f"{fn}.json", j)
            # Stats txt
            num = df.select_dtypes(include="number")
            if len(num.columns):
                zf.writestr("statistics.txt", num.describe().round(4).to_string())
        buf.seek(0)
        return send_file(buf, download_name=f"{fn}_bundle.zip",
                         as_attachment=True, mimetype="application/zip")
    except Exception as e:
        return jsonify(error=str(e)), 500

@export_bp.route("/powerbi-mquery")
def export_powerbi():
    store = get_store()
    df = store.get("df")
    if df is None: return jsonify(error="No dataset"), 400
    fn = store.get("filename","dataset")
    cols = list(df.columns)
    col_types = []
    for c in cols:
        dt = str(df[c].dtype)
        if "int" in dt: pbi_type = "Int64.Type"
        elif "float" in dt: pbi_type = "type number"
        elif "datetime" in dt: pbi_type = "type datetime"
        else: pbi_type = "type text"
        col_types.append(f'{{"{c}", {pbi_type}}}')
    col_types_str = ",\n            ".join(col_types)
    m_query = f"""let
    Source = Csv.Document(File.Contents("{fn}"), [Delimiter=",", Columns={len(cols)}, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    ChangedTypes = Table.TransformColumnTypes(PromoteHeaders, {{
        {col_types_str}
    }})
in
    ChangedTypes"""
    dax = _generate_dax(df)
    resp = make_response(json.dumps({"m_query": m_query, "dax_measures": dax}, indent=2))
    resp.headers["Content-Type"] = "application/json"
    resp.headers["Content-Disposition"] = "attachment; filename=powerbi_config.json"
    return resp

def _generate_dax(df):
    measures = []
    num_cols = df.select_dtypes(include="number").columns
    for c in num_cols[:5]:
        measures.append(f"Total {c} = SUM('{c}'[{c}])")
        measures.append(f"Avg {c} = AVERAGE('{c}'[{c}])")
    return measures

@export_bp.route("/info")
def export_info():
    store = get_store()
    df = store.get("df")
    return jsonify(loaded=df is not None,
                   filename=store.get("filename"),
                   rows=len(df) if df is not None else 0,
                   cols=len(df.columns) if df is not None else 0)
